export const salaryHijackingDesignSystem = {
  colors: {
    brand: {
      primary: "#209252",
      primaryPressed: "#005229",
      secondary: "#2FA86A",
      primarySoft: "#EAF6EF",
      surface: "#D9F0E3",
      tint: "#A7E7C1",
      dark: "#12663A",
    },
    text: {
      primary: "#202327",
      secondary: "#6D737A",
      muted: "#7A867F",
      disabled: "#ADB3B8",
      inverse: "#FFFFFF",
    },
    surface: {
      default: "#FFFFFF",
      subtle: "#F7F9FA",
      raised: "#FFFFFF",
      elevated: "#FFFFFF",
      soft: "#F8FAF9",
    },
    border: {
      default: "#E7EBEF",
      strong: "#DDE8DE",
      soft: "#EEF0F2",
    },
    semantic: {
      success: "#209252",
      warning: "#F7D34D",
      warningSoft: "#FFF8ED",
      warningStrong: "#F59E0B",
      danger: "#D74B4B",
      dangerSoft: "#FDECEC",
      dangerStrong: "#BA1A1A",
      info: "#316B5D",
    },
    overlay: "rgba(32, 35, 39, 0.42)",
    shadow: "rgba(6, 38, 20, 0.12)",
  },
  font: {
    family:
      'var(--font-presentation), "Presentation", "Pretendard", "Noto Sans KR", system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    native: {
      regular: "Freesentation-4Regular",
      medium: "Freesentation-4Regular",
      semibold: "Freesentation-7Bold",
      bold: "Freesentation-7Bold",
      extraBold: "Freesentation-7Bold",
      black: "Freesentation-7Bold",
    },
    weight: {
      regular: "400",
      medium: "500",
      semibold: "600",
      bold: "700",
      heavy: "800",
    },
  },
  typography: {
    display: {
      fontSize: 34,
      lineHeight: 42,
      fontWeight: "800",
      letterSpacing: 0,
    },
    titleXL: {
      fontSize: 26,
      lineHeight: 34,
      fontWeight: "800",
      letterSpacing: 0,
    },
    titleL: {
      fontSize: 22,
      lineHeight: 30,
      fontWeight: "700",
      letterSpacing: 0,
    },
    titleM: {
      fontSize: 18,
      lineHeight: 26,
      fontWeight: "700",
      letterSpacing: 0,
    },
    bodyL: {
      fontSize: 16,
      lineHeight: 24,
      fontWeight: "500",
      letterSpacing: 0,
    },
    bodyM: {
      fontSize: 15,
      lineHeight: 22,
      fontWeight: "500",
      letterSpacing: 0,
    },
    bodyS: {
      fontSize: 14,
      lineHeight: 20,
      fontWeight: "500",
      letterSpacing: 0,
    },
    labelL: {
      fontSize: 15,
      lineHeight: 22,
      fontWeight: "700",
      letterSpacing: 0,
    },
    labelM: {
      fontSize: 13,
      lineHeight: 18,
      fontWeight: "700",
      letterSpacing: 0,
    },
    labelS: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "700",
      letterSpacing: 0,
    },
    caption: {
      fontSize: 12,
      lineHeight: 18,
      fontWeight: "500",
      letterSpacing: 0,
    },
    amountXL: {
      fontSize: 34,
      lineHeight: 42,
      fontWeight: "800",
      letterSpacing: 0,
    },
    amountL: {
      fontSize: 26,
      lineHeight: 34,
      fontWeight: "800",
      letterSpacing: 0,
    },
    amountM: {
      fontSize: 20,
      lineHeight: 28,
      fontWeight: "700",
      letterSpacing: 0,
    },
  },
  spacing: {
    0: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    8: 32,
    10: 40,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 22,
    full: 999,
  },
  elevation: {
    none: {
      shadowOpacity: 0,
      elevation: 0,
    },
    low: {
      shadowColor: "#0F2319",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.06,
      shadowRadius: 24,
      elevation: 2,
    },
    medium: {
      shadowColor: "#0F2319",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.12,
      shadowRadius: 28,
      elevation: 5,
    },
    high: {
      shadowColor: "#209252",
      shadowOffset: { width: 0, height: 14 },
      shadowOpacity: 0.24,
      shadowRadius: 34,
      elevation: 8,
    },
  },
  navigation: {
    bottomTabs: {
      labels: ["홈", "계획", "LV UP", "커뮤니티", "MY"],
      visualHeight: 74,
      safeAreaAware: true,
      iconSize: 22,
      activeColor: "#209252",
      inactiveColor: "#ADB3B8",
      background: "#FFFFFF",
      borderColor: "#E7EBEF",
      labelTypography: "labelS",
    },
  },
  providerBrand: {
    facebook: "#1877F2",
    google: "#FFFFFF",
    kakao: "#FEE500",
    naver: "#03C75A",
  },
  header: {
    variants: ["ROOT", "BACK", "TITLE", "TITLE_ACTION", "TRANSPARENT"],
    height: 56,
    titleTypography: "titleM",
    actionSize: 44,
    dividerColor: "#E7EBEF",
  },
  components: {
    buttons: [
      "PrimaryButton",
      "SecondaryButton",
      "TertiaryButton",
      "IconButton",
    ],
    fields: ["TextField", "AmountField", "SearchField", "SelectField"],
    cards: ["Card", "FinanceHeroCard", "MetricCard", "ContentCard"],
    lists: ["ListRow", "FinanceListRow", "SettingListRow"],
    states: [
      "Skeleton",
      "EmptyState",
      "ErrorState",
      "OfflineState",
      "PermissionState",
    ],
    overlays: [
      "Modal",
      "ConfirmationModal",
      "DestructiveModal",
      "BottomSheet",
      "SelectSheet",
      "AmountSheet",
      "Toast",
      "Snackbar",
      "FAB",
    ],
  },
  layout: {
    mobileWidth: 390,
    maxMobileWidth: 430,
    touchTarget: 44,
  },
} as const;

export const componentColors = {
  background: salaryHijackingDesignSystem.colors.surface.subtle,
  surface: salaryHijackingDesignSystem.colors.surface.default,
  surfaceSoft: salaryHijackingDesignSystem.colors.surface.soft,
  surfaceRaised: salaryHijackingDesignSystem.colors.surface.raised,
  primaryGreen: salaryHijackingDesignSystem.colors.brand.primary,
  primaryGreenDark: salaryHijackingDesignSystem.colors.brand.primaryPressed,
  primaryGreenSoft: salaryHijackingDesignSystem.colors.brand.primarySoft,
  primaryGreenTint: salaryHijackingDesignSystem.colors.brand.tint,
  textPrimary: salaryHijackingDesignSystem.colors.text.primary,
  textSecondary: salaryHijackingDesignSystem.colors.text.secondary,
  textMuted: salaryHijackingDesignSystem.colors.text.muted,
  line: salaryHijackingDesignSystem.colors.border.default,
  warningYellow: salaryHijackingDesignSystem.colors.semantic.warning,
  warningOrange: salaryHijackingDesignSystem.colors.semantic.warningStrong,
  dangerRed: salaryHijackingDesignSystem.colors.semantic.danger,
  disabledGray: salaryHijackingDesignSystem.colors.text.disabled,
  shadow: salaryHijackingDesignSystem.colors.shadow,
} as const;

export const componentRadius = {
  card: salaryHijackingDesignSystem.radius.lg,
  button: salaryHijackingDesignSystem.radius.md,
  pill: salaryHijackingDesignSystem.radius.full,
  modal: salaryHijackingDesignSystem.radius.xl,
} as const;

export const componentSpacing = {
  xs: salaryHijackingDesignSystem.spacing[1],
  sm: salaryHijackingDesignSystem.spacing[2],
  md: salaryHijackingDesignSystem.spacing[4],
  lg: salaryHijackingDesignSystem.spacing[5],
  xl: salaryHijackingDesignSystem.spacing[8],
  xxl: salaryHijackingDesignSystem.spacing[10],
} as const;

export const componentTypography = {
  heroAmount: salaryHijackingDesignSystem.typography.amountXL.fontSize,
  title: salaryHijackingDesignSystem.typography.titleXL.fontSize,
  sectionTitle: salaryHijackingDesignSystem.typography.titleM.fontSize,
  body: salaryHijackingDesignSystem.typography.bodyM.fontSize,
  caption: salaryHijackingDesignSystem.typography.caption.fontSize,
  button: salaryHijackingDesignSystem.typography.labelL.fontSize,
} as const;
