import { salaryHijackingDesignSystem } from "../components/tokens";

const designSystem = salaryHijackingDesignSystem;

export const salaryHijackingTheme = {
  name: "Salary Hijacking Clean Fintech v1",
  font: designSystem.font,
  color: {
    brand: {
      primary: designSystem.colors.brand.primary,
      secondary: designSystem.colors.brand.secondary,
      soft: designSystem.colors.brand.primarySoft,
      soft2: designSystem.colors.brand.surface,
      dark: designSystem.colors.brand.dark,
    },
    semantic: {
      success: designSystem.colors.semantic.success,
      warning: designSystem.colors.semantic.warning,
      danger: designSystem.colors.semantic.danger,
      info: designSystem.colors.semantic.info,
    },
    text: {
      primary: designSystem.colors.text.primary,
      secondary: designSystem.colors.text.secondary,
      muted: designSystem.colors.text.muted,
      disabled: designSystem.colors.text.disabled,
      inverse: designSystem.colors.text.inverse,
    },
    surface: {
      app: designSystem.colors.surface.subtle,
      card: designSystem.colors.surface.default,
      soft: designSystem.colors.surface.soft,
      elevated: designSystem.colors.surface.elevated,
      line: designSystem.colors.border.default,
      lineSoft: designSystem.colors.border.soft,
    },
  },
  radius: {
    xs: designSystem.radius.sm,
    sm: designSystem.radius.md,
    md: designSystem.radius.lg,
    lg: designSystem.radius.xl,
    xl: 24,
    full: designSystem.radius.full,
  },
  spacing: {
    0: designSystem.spacing[0],
    2: 2,
    4: designSystem.spacing[1],
    6: 6,
    8: designSystem.spacing[2],
    10: 10,
    12: designSystem.spacing[3],
    16: designSystem.spacing[4],
    20: designSystem.spacing[5],
    24: designSystem.spacing[6],
    32: designSystem.spacing[8],
    40: designSystem.spacing[10],
  },
  typography: {
    display: designSystem.typography.display,
    title1: designSystem.typography.titleXL,
    title2: designSystem.typography.titleL,
    headline: designSystem.typography.titleM,
    body: designSystem.typography.bodyM,
    caption: designSystem.typography.caption,
  },
  shadow: {
    card: designSystem.elevation.low,
    floating: designSystem.elevation.high,
  },
  layout: {
    mobileWidth: designSystem.layout.mobileWidth,
    maxMobileWidth: designSystem.layout.maxMobileWidth,
    bottomTabHeight: 76,
    bottomTabVisualHeight: designSystem.navigation.bottomTabs.visualHeight,
    headerHeight: designSystem.header.height,
    touchTarget: designSystem.layout.touchTarget,
  },
} as const;

export const appIcons = {
  salary: "💸",
  plan: "🧾",
  level: "⬆️",
  community: "💬",
  my: "👤",
  notification: "🔔",
  settings: "⚙️",
  write: "✍️",
  saving: "🏦",
  expense: "💳",
  budget: "📊",
  success: "✅",
  warning: "⚠️",
  reward: "🎁",
  reading: "📚",
  news: "📰",
  english: "🎧",
  health: "🏃",
  coffee: "☕",
  meal: "🍱",
  subscription: "🔁",
} as const;
