export const salaryHijackingTheme = {
  name: "Salary Hijacking Clean Fintech v1",
  font: {
    family:
      'var(--font-presentation), "Presentation", "Pretendard", "Noto Sans KR", system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    native: {
      regular: "Freesentation-4Regular",
      medium: "Freesentation-5Medium",
      semibold: "Freesentation-6SemiBold",
      bold: "Freesentation-7Bold",
      extraBold: "Freesentation-8ExtraBold",
      black: "Freesentation-9Black",
    },
    weight: {
      regular: "400",
      medium: "500",
      semibold: "600",
      bold: "700",
      heavy: "800",
    },
  },
  color: {
    brand: {
      primary: "#209252",
      secondary: "#2FA86A",
      soft: "#EAF6EF",
      soft2: "#D9F0E3",
      dark: "#12663A",
    },
    semantic: {
      success: "#209252",
      warning: "#F7D34D",
      danger: "#D74B4B",
      info: "#4285F4",
    },
    text: {
      primary: "#202327",
      secondary: "#4B535B",
      muted: "#6D737A",
      disabled: "#ADB3B8",
      inverse: "#FFFFFF",
    },
    surface: {
      app: "#F7F8FA",
      card: "#FFFFFF",
      soft: "#F8FAF9",
      elevated: "#FFFFFF",
      line: "#E7EBEF",
      lineSoft: "#EEF0F2",
    },
  },
  radius: {
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    full: 999,
  },
  spacing: {
    0: 0,
    2: 2,
    4: 4,
    6: 6,
    8: 8,
    10: 10,
    12: 12,
    16: 16,
    20: 20,
    24: 24,
    32: 32,
    40: 40,
  },
  typography: {
    display: {
      fontSize: 34,
      lineHeight: 42,
      fontWeight: "800",
      letterSpacing: 0,
    },
    title1: {
      fontSize: 26,
      lineHeight: 34,
      fontWeight: "800",
      letterSpacing: 0,
    },
    title2: {
      fontSize: 22,
      lineHeight: 30,
      fontWeight: "700",
      letterSpacing: 0,
    },
    headline: {
      fontSize: 18,
      lineHeight: 26,
      fontWeight: "700",
      letterSpacing: 0,
    },
    body: {
      fontSize: 15,
      lineHeight: 22,
      fontWeight: "500",
      letterSpacing: 0,
    },
    caption: {
      fontSize: 12,
      lineHeight: 18,
      fontWeight: "500",
      letterSpacing: 0,
    },
  },
  shadow: {
    card: {
      shadowColor: "#0F2319",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.06,
      shadowRadius: 24,
      elevation: 2,
    },
    floating: {
      shadowColor: "#209252",
      shadowOffset: { width: 0, height: 14 },
      shadowOpacity: 0.24,
      shadowRadius: 34,
      elevation: 8,
    },
  },
  layout: {
    mobileWidth: 390,
    maxMobileWidth: 430,
    bottomTabHeight: 76,
    headerHeight: 56,
    touchTarget: 44,
  },
} as const;

export const appIcons = {
  salary: "💸",
  plan: "🧾",
  level: "⬆️",
  community: "💬",
  my: "👤",
  notification: "🔔",
  settings: "⚙️",
  write: "✍️",
  saving: "🏦",
  expense: "💳",
  budget: "📊",
  success: "✅",
  warning: "⚠️",
  reward: "🎁",
  reading: "📚",
  news: "📰",
  english: "🎧",
  health: "🏃",
  coffee: "☕",
  meal: "🍱",
  subscription: "🔁",
} as const;
